### PR TITLE
Do not keep going if step fails.

### PR DESCRIPTION
**Pull request by vaikas**
#### Summary
I am trying to see if this will invoke the pager if the step fails.

### CODE REVIEW

**Comment by haydentherapper** [comment]
I _think_ this would resolve it.

**Comment by vaikas** [comment]
So, I ran this manually and it created this alert as expected:
https://github.com/sigstore/sigstore-probers/actions/runs/4546522181/attempts/1

Somehow the 2022-2 failed also, but worked on retry.

Triggered this alert:
https://sigstore.pagerduty.com/incidents/Q0XQ35N7MKA1C3

**Comment by vaikas** [comment]
This fixes:
https://github.com/sigstore/public-good-instance/issues/1090

But until we fix the public key issue, we shouldn't merge this :)

**Comment by vaikas** [comment]
@haydentherapper I'm going to merge this now since the underlying issue has been fixed.

**Pull request merged**
